apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: arex21j60-nodejs 
  janus-idp.io/tekton: arex21j60-nodejs
  backstage.io/kubernetes-id: arex21j60-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: arex21j60-nodejs
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml